# The URL the site will be built for
base_url = "https://kranurag78.github.io/zola-hook"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Hook"
description = "Hook is a theme for Zola"

taxonomies = [
  {name = "categories"},
  {name = "tags"},
]

[markdown]

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "monokai"

[extra]
# Put all your custom variables here

# latest posts determines how many latest posts to show on homepage
latest_posts = 5

main_menu = [
  {name = "Home", url = "/"},
  {name = "Blogs", url = "/blog"},
  {name = "Snippets", url = "/snippets"},
]

